# Force Railway to use Nixpacks (NOT Docker) - Updated
[variables]
JAVA_VERSION = "21"

[phases.setup]
nixPkgs = ["jdk21", "maven"]

[phases.build]
cmds = [
  "mvn --version",
  "mvn clean package -DskipTests -Dspring.profiles.active=railway",
  "ls -la target/",
  "chmod +x start.sh"
]

[phases.start]
cmd = "./start.sh"
