[build]
builder = "NIXPACKS"
buildCommand = "mvn clean package -DskipTests"

[deploy]
startCommand = "java -Dserver.port=$PORT -jar target/backend-spring-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
